language: node_js
sudo: false
node_js: stable
addons:
  sources:
    - google-chrome
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
  chrome: stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- 'if [ "$CMD" == "test" ] && [ "TRAVIS_BRANCH" == "master" ]; then
      webdriver-manager update;
  fi'
- npm start &
- sleep 60
notifications:
  email: false
