language: node_js
sudo: false
node_js: stable
addons:
  chrome: stable
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- webdriver-manager update
- npm start &
- sleep 60
notifications:
  email: false
