sudo: required
dist: trusty
group: edge
language: node_js
node_js:
- stable
- 7
- 6
matrix:
  allow_failures:
    - node_js: stable
addons:
  sources:
    - google-chrome
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - google-chrome-stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- npm start &
- sleep 60
notifications:
  email: false
