language: node_js
sudo: false
node_js: 8
addon:
  firefox: latest
  chrome: stable
env:
  matrix:
  - CMD=test
  - CMD=build
  - CMD=lint
cache:
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- 'if [ "$CMD" == "test" ]; then
      webdriver-manager update;
  fi'
- npm start &
- sleep 60
script:
- npm run $CMD
after_success:
- '[ "$CMD" == "test" ] && npm run coverage'
notifications:
  email: false
